### PR TITLE
Issues 2,3,4,5 fix

### LINKED ISSUE #2: Replace Matcher<type> to Matcher<? super type> for arguments in check methods
**Now:**
```
public Trololo checkA(Matcher<String> matcher) {
...
}
```
When we call the method and pass (for example) _notNullValue_ matcher as argument - we **have to** pass it  in the following manner _notNullValue(**String.class**)_

If generator will generate method in the following manner:
```
public Trololo checkA(Matcher<? super String> matcher) {
...
}
```
we will not have to pass _notNullValue(**String.class**)_ - it will enough _notNullValue()_

### LINKED ISSUE #3: Check methods haven't generated for fields of superclass
it will be useful to generate it.

### LINKED ISSUE #4: Replace modifier protected to public for method - String getRequestName()

### LINKED ISSUE #5: Generate 2nd arg as Supplier for method setWsdlLocation
**Now**
    public ASteps() {
        super.setWsdlLocation(AService.class, **_""_**));
        getPort();
    }

**Suggestion**
    public ASteps() {
        super.setWsdlLocation(AService.class, **_() ->_**""));
        getPort();
    }

### PR DESCRIPTION
**Pull request by lexezzz**

### CODE REVIEW

File: soapStepsGenerator/src/main/java/com/iterexoff/soapStepsGenerator/utils/ClassUtils.java [hunk 1]
```diff
@@ -175,4 +175,12 @@ public static String getGetterMethodNameForField(Class<?> classWithField, Field
             return "get" + capitalizedFieldName;
         }
     }
+
+    public static List<Field> getDeclaredFieldsWithSuperclasses(Class<?> inputClass) {
+        List<Field> fields = new LinkedList<>();
+        for (Class<?> clazz = inputClass; clazz != Object.class; clazz = clazz.getSuperclass()) {
```
Comment (ITerexoff) [inline soapStepsGenerator/src/main/java/com/iterexoff/soapStepsGenerator/utils/ClassUtils.java:181]: If clazz will extend from... for example, any Java class - may be it will not a good decision to generate steps for standart fields of Java class, 
But, ok. Let's left it now.

File: soapStepsGenerator/src/main/java/com/iterexoff/soapStepsGenerator/utils/ClassUtils.java [hunk 2]
```diff
@@ -175,4 +175,12 @@ public static String getGetterMethodNameForField(Class<?> classWithField, Field
             return "get" + capitalizedFieldName;
         }
     }
+
+    public static List<Field> getDeclaredFieldsWithSuperclasses(Class<?> inputClass) {
+        List<Field> fields = new LinkedList<>();
```
Comment (ITerexoff) [inline soapStepsGenerator/src/main/java/com/iterexoff/soapStepsGenerator/utils/ClassUtils.java]: ArrayList?

**Review by ITerexoff — COMMENTED** [review]
Please upgrade patch version in pom.xml

**Review by ITerexoff — APPROVED** [review]
